# This file is autogenerated by the command `make fix-copies`, do not edit.
# flake8: noqa

from . import DummyObject, requires_backends


class LDMTextToImagePipeline(metaclass=DummyObject):
    _backends = ["paddlenlp"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddlenlp"])


class StableDiffusionImg2ImgPipeline(metaclass=DummyObject):
    _backends = ["paddlenlp"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddlenlp"])


class StableDiffusionInpaintPipeline(metaclass=DummyObject):
    _backends = ["paddlenlp"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddlenlp"])


class StableDiffusionPipeline(metaclass=DummyObject):
    _backends = ["paddlenlp"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddlenlp"])
