# This file is autogenerated by the command `make fix-copies`, do not edit.
# flake8: noqa
from . import DummyObject, requires_backends


class GradTTSPipeline(metaclass=DummyObject):
    _backends = ["paddlenlp", "inflect", "unidecode"]

    def __init__(self, *args, **kwargs):
        requires_backends(self, ["paddlenlp", "inflect", "unidecode"])
